//
// Created by vsweatherfield on 2021-09-15.
//

#ifndef PDP11_EMULATOR_EMULATORCONSTANTS_H
#define PDP11_EMULATOR_EMULATORCONSTANTS_H

#define DEFAULT_STARTING_ADDRESS 01000

#define NOT_FINISHED 0
#define FINISHED 1

#define IMMEDIATE_MODE 0
#define STEP_MODE 1

#endif // PDP11_EMULATOR_EMULATORCONSTANTS_H